class QStandardItem:
    def __init__(self, text: str = ...) -> None: ...
    def appendRow(self, item: 'QStandardItem') -> None: ...
    def rowCount(self) -> int: ...
    def child(self, row: int): ...
    def removeRow(self, row: int) -> None: ...
    def data(self, role: int): ...
    def setData(self, value, role: int) -> None: ...
    def setEditable(self, val: bool) -> None: ...

class QStandardItemModel:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def setHorizontalHeaderLabels(self, labels) -> None: ...
    def appendRow(self, item: QStandardItem) -> None: ...
    def invisibleRootItem(self) -> QStandardItem: ...
    def itemFromIndex(self, index) -> QStandardItem: ...
