# python/gui/localization.py

TRANSLATIONS = {
    # Window & Menus
    "Card Editor": "カードエチE��タ",
    "Load from JSON": "JSONから読み込み",
    "Save to JSON": "JSONへ保孁E,
    "File": "ファイル",
    "Edit": "編雁E,
    "Open": "開く",
    "Save": "保孁E,
    "Close": "閉じめE,
    "New Card": "新規カーチE,
    "Delete Card": "カード削除",
    "Delete Item": "削除",
    "Preview": "プレビュー",
    "Action updated!": "アクションが更新されました�E�E,
    "Cards saved successfully!": "カードが正常に保存されました�E�E,
    "Error": "エラー",
    "Success": "成功",
    "Failed to load JSON": "JSONの読み込みに失敗しました",
    "Failed to save JSON": "JSONの保存に失敗しました",
    "Property Inspector": "プロパティ・インスペクタ",
    "Select an item to edit": "編雁E��る頁E��を選択してください",
    "Main Toolbar": "メインチE�Eルバ�E",
    "Tools": "チE�Eル",
    "Batch Simulation": "バッチシミュレーション",
    "Scenario Editor": "シナリオエチE��タ",

    # Batch Simulation
    "Batch Simulation / Verification": "バッチシミュレーション / 検証",
    "Settings": "設宁E,
    "Scenario": "シナリオ",
    "Evaluator": "評価器 (Evaluator)",
    "Games": "ゲーム数",
    "Threads": "スレチE��数",
    "MCTS Sims": "MCTSシミュレーション数",
    "Run Simulation": "シミュレーション開姁E,
    "Cancel": "キャンセル",
    "Starting simulation": "シミュレーションを開始しまぁE,
    "Completed": "完亁E,
    "Wins": "勝利",
    "Losses": "敗北",
    "Draws": "引き刁E��",
    "Throughput": "スループッチE,
    "Simulation Error": "シミュレーションエラー",
    "Warning: No model_v1.pth found. Using random weights.": "警呁E model_v1.pthが見つかりません。ランダムな重みを使用します、E,

    # Scenario Editor
    "Scenarios": "シナリオ一覧",
    "Name (ID)": "名前 (ID)",
    "Description": "説昁E,
    "Configuration (JSON)": "設宁E(JSON)",
    "Save All to File": "ファイルに保孁E,
    "Scenarios saved successfully!": "シナリオが正常に保存されました�E�E,
    "New": "新規作�E",
    "Delete": "削除",

    # Card Details
    "Card Details": "カード詳細",
    "ID": "ID",
    "Name": "名前",
    "Cost": "コスチE,
    "Civilization": "斁E�E",
    "Power": "パワー",
    "Type": "タイチE,
    "Races": "種旁E,
    "Twinpact": "チE��ンパクチE,
    "Edit Spell Side": "呪斁E�Eを編雁E,

    # Lists & Groups
    "Keywords": "キーワード�E劁E,
    "Effects": "効果リスチE,
    "Add Effect": "効果を追加",
    "Remove Effect": "効果を削除",
    "Reaction Abilities": "リアクション能劁E, # Ninja Strike etc
    "REVOLUTION_CHANGE": "革命チェンジ",

    # Effect Definition
    "Effect": "効极E,
    "Trigger": "トリガー",
    "Condition": "発動条件",
    "Actions": "アクションリスチE,
    "Add Action": "アクションを追加",
    "Remove Action": "アクションを削除",

    # Action Definition
    "Action": "アクション",
    "Action Type": "アクションタイチE,
    "Scope": "対象篁E�� (Scope)",
    "Target Player": "対象プレイヤー",
    "Source Zone": "移動�Eゾーン",
    "Destination Zone": "移動�Eゾーン",
    "Value 1": "値 1 (数)",
    "Value 2": "値 2",
    "String Value": "斁E���E値",
    "Input Key": "入力変数キー",
    "Output Key": "出力変数キー",
    "Optional": "任意効极E,
    "Update Action": "アクション更新",
    "Reduction Amount": "軽減量",
    "Duration (Turns)": "持続ターン",

    # Filter Definition
    "Filter": "フィルタ",
    "Owner": "所有老E,
    "Zones": "ゾーン",
    "Card Types": "カードタイチE,
    "Civilizations": "斁E�Eフィルタ",
    "Races": "種族フィルタ",
    "Min Cost": "最小コスチE,
    "Max Cost": "最大コスチE,
    "Min Power": "最小パワー",
    "Max Power": "最大パワー",
    "Min": "最封E,
    "Max": "最大",
    "Tapped": "タチE�E状慁E,
    "Blocker": "ブロチE��ー",
    "Evolution": "進匁E,
    "Count": "枚数",
    "Ignore": "持E��なぁE,
    "True": "はぁE,
    "False": "ぁE��ぁE,
    "Selection Mode": "選択モーチE,
    "All/Any": "すべて / 任愁E,
    "Fixed Number": "枚数持E��E,

    # Common Values
    "NONE": "なぁE,
    "CREATURE": "クリーチャー",
    "SPELL": "呪斁E,
    "EVOLUTION_CREATURE": "進化クリーチャー",
    "LIGHT": "允E,
    "WATER": "水",
    "DARKNESS": "闁E,
    "FIRE": "火",
    "NATURE": "自然",
    "ZERO": "ゼロ",

    # Enums - Triggers
    "ON_PLAY": "登場晁E(ON_PLAY)",
    "ON_ATTACK": "攻撁E�� (ON_ATTACK)",
    "ON_DESTROY": "破壊時 (ON_DESTROY)",
    "S_TRIGGER": "S・トリガー",
    "TURN_START": "ターン開始時",
    "PASSIVE_CONST": "常在効极E,
    "ON_OTHER_ENTER": "他クリーチャー登場晁E,
    "ON_ATTACK_FROM_HAND": "手札から攻撁E�� (革命チェンジ筁E",
    "AT_BREAK_SHIELD": "シールドブレイク晁E,

    # Enums - Conditions
    "MANA_ARMED": "マナ武裁E,
    "SHIELD_COUNT": "シールド枚数",
    "CIVILIZATION_MATCH": "斁E�E一致",
    "OPPONENT_PLAYED_WITHOUT_MANA": "相手がマナを払わずにプレイ",
    "DURING_YOUR_TURN": "自刁E�Eターン中",
    "DURING_OPPONENT_TURN": "相手�Eターン中",
    "FIRST_ATTACK": "こ�Eターン最初�E攻撁E,

    # Enums - Actions
    "DRAW_CARD": "ドロー",
    "ADD_MANA": "マナ加送E,
    "DESTROY": "破壁E,
    "RETURN_TO_HAND": "手札に戻ぁE(バウンス)",
    "SEND_TO_MANA": "マナ送りにする",
    "TAP": "タチE�Eする",
    "UNTAP": "アンタチE�Eする",
    "MODIFY_POWER": "パワー修正",
    "BREAK_SHIELD": "シールドブレイク",
    "LOOK_AND_ADD": "見て手札に加える",
    "SUMMON_TOKEN": "ト�Eクン召喁E,
    "SEARCH_DECK_BOTTOM": "山札下サーチE,
    "MEKRAID": "メクレイチE,
    "DISCARD": "手札を捨てめE,
    "PLAY_FROM_ZONE": "ゾーンからプレイ",
    "COST_REFERENCE": "コスト参照 (自身を軽渁E",
    "COST_REDUCTION": "コスト軽渁E(他を軽渁E",
    "LOOK_TO_BUFFER": "バッファへ見る",
    "SELECT_FROM_BUFFER": "バッファから選抁E,
    "PLAY_FROM_BUFFER": "バッファからプレイ",
    "MOVE_BUFFER_TO_ZONE": "バッファから移勁E,
    "REVOLUTION_CHANGE": "革命チェンジ",
    "COUNT_CARDS": "カードを数える",
    "GET_GAME_STAT": "ゲーム統計取征E,
    "APPLY_MODIFIER": "修正を適用 (継続効极E",
    "REVEAL_CARDS": "カードを公閁E,
    "REGISTER_DELAYED_EFFECT": "遁E��効果登録",
    "RESET_INSTANCE": "カード状態リセチE��",
    "Hyper Energy": "ハイパ�Eエナジー",
    "SEND_TO_DECK_BOTTOM": "山札下へ送る",
    "SELECT_NUMBER": "数字を選抁E,
    "FRIEND_BURST": "フレンド�Eバ�EスチE,

    # Smart Link
    "Use result from previous measurement": "直前�E計測結果を使用する",
    "Cards matching filter": "フィルターに一致する枚数",

    # Game Stats
    "MANA_CIVILIZATION_COUNT": "マナゾーンの斁E�E数",
    "SHIELD_COUNT": "シールド枚数",
    "HAND_COUNT": "手札枚数",
    "CARDS_DRAWN_THIS_TURN": "こ�Eターンに引いたカード�E枚数",

    # UI Labels
    "Mode": "モーチE,

    # Filter Help
    "Filter Help": "対象を選択するゾーンを指定してください。「枚数」を0にすると「すべて/任意」になります、E以上にするとそ�E枚数を選択します、E,

    # Scope
    "SELF": "自身(カーチE",
    "PLAYER_SELF": "自刁Eプレイヤー)",
    "PLAYER_OPPONENT": "相扁E,
    "TARGET_SELECT": "選抁E,
    "ALL_PLAYERS": "両老E,
    "RANDOM": "ランダム",
    "ALL_FILTERED": "全て(フィルタ)",

    # Zones
    "BATTLE_ZONE": "バトルゾーン",
    "MANA_ZONE": "マナゾーン",
    "HAND": "手札",
    "GRAVEYARD": "墓地",
    "SHIELD_ZONE": "シールドゾーン",
    "DECK": "山札",

    # Keywords
    "Speed Attacker": "スピ�EドアタチE��ー",
    "Blocker": "ブロチE��ー",
    "Slayer": "スレイヤー",
    "Double Breaker": "W・ブレイカー",
    "Triple Breaker": "T・ブレイカー",
    "Shield Trigger": "S・トリガー",
    "Just Diver": "ジャストダイバ�E",
    "Mach Fighter": "マッハファイター",
    "G Strike": "G・ストライク",
    "Evolution": "進匁E,
}

def tr(text):
    return TRANSLATIONS.get(text, text)
