# Simple localization placeholder. Keep ASCII to avoid encoding issues.
TRANSLATIONS = {
    # Action Types
    "GRANT_KEYWORD": "キーワード付与",
    "MOVE_CARD": "カード移動",
    "FRIEND_BURST": "フレンド・バースト",
    "LOCK_SPELL": "呪文ロック",
    "APPLY_MODIFIER": "効果付与",
    "PLAY_CARD": "カードをプレイ",
    "DRAW_CARD": "カードを引く",
    "ADD_MANA": "マナ追加",
    "DESTROY": "破壊",
    "RETURN_TO_HAND": "手札に戻す",
    "SEND_TO_MANA": "マナ送りにする",
    "TAP": "タップする",
    "UNTAP": "アンタップする",
    "MODIFY_POWER": "パワー修正",
    "BREAK_SHIELD": "シールドブレイク",
    "LOOK_AND_ADD": "見て加える(サーチ)",
    "SEARCH_DECK_BOTTOM": "デッキ下サーチ",
    "MEKRAID": "メクレイド",
    "REVOLUTION_CHANGE": "革命チェンジ",
    "COUNT_CARDS": "カードカウント",
    "GET_GAME_STAT": "ゲーム統計取得",
    "REVEAL_CARDS": "カード公開",
    "RESET_INSTANCE": "カード状態リセット",
    "REGISTER_DELAYED_EFFECT": "遅延効果登録",
    "SEARCH_DECK": "デッキ探索",
    "SHUFFLE_DECK": "デッキシャッフル",
    "ADD_SHIELD": "シールド追加",
    "SEND_SHIELD_TO_GRAVE": "シールド焼却",
    "SEND_TO_DECK_BOTTOM": "デッキ下へ送る",
    "MOVE_TO_UNDER_CARD": "カードの下に重ねる",
    "CAST_SPELL": "呪文を唱える",
    "PUT_CREATURE": "クリーチャーを出す",
    "COST_REFERENCE": "コスト参照/軽減",
    "SELECT_NUMBER": "数字を選択",
    "SUMMON_TOKEN": "トークン生成",
    "DISCARD": "手札を捨てる",
    "PLAY_FROM_ZONE": "ゾーンからプレイ",
    "MEASURE_COUNT": "カウント/計測",
    "COST_REDUCTION": "コスト軽減",
    "LOOK_TO_BUFFER": "バッファへ移動(Look)",
    "SELECT_FROM_BUFFER": "バッファから選択",
    "PLAY_FROM_BUFFER": "バッファからプレイ",
    "MOVE_BUFFER_TO_ZONE": "バッファから移動",
    "SELECT_OPTION": "選択肢",
    "DECLARE_NUMBER": "数字宣言",

    # Measure Modes
    "CARDS_MATCHING_FILTER": "条件に合うカード数",
    "MANA_CIVILIZATION_COUNT": "マナ文明数",
    "SHIELD_COUNT": "シールド枚数",
    "HAND_COUNT": "手札枚数",
    "CARDS_DRAWN_THIS_TURN": "ターン内ドロー枚数",

    # Ref Modes
    "SYM_CREATURE": "シンパシー: クリーチャー",
    "SYM_SPELL": "シンパシー: 呪文",
    "HYPER_ENERGY": "ハイパーエナジー",
    "G_ZERO": "G・ゼロ",

    # Triggers
    "ON_PLAY": "出た時 (CIP)",
    "ON_ATTACK": "攻撃する時",
    "ON_DESTROY": "破壊された時",
    "S_TRIGGER": "S・トリガー",
    "TURN_START": "ターン開始時",
    "PASSIVE_CONST": "常在効果(パッシブ)",
    "ON_BLOCK": "ブロックした時",
    "AT_END_OF_TURN": "ターン終了時",
    "AT_START_OF_TURN": "ターン開始時",
    "AT_ATTACK": "攻撃時",
    "AT_BLOCK": "ブロック時",
    "G_STRIKE": "G・ストライク",
    "ON_OPPONENT_DRAW": "相手がカードを引いたとき",
    "ON_CAST_SPELL": "この呪文を唱えた時",
    "ON_SHIELD_ADD": "シールドが加わった時",
    "AT_BREAK_SHIELD": "シールドブレイク時",
    "ON_OTHER_ENTER": "他のクリーチャーが出た時",
    "ON_ATTACK_FROM_HAND": "手札から攻撃する時",

    # Reactions
    "NINJA_STRIKE": "ニンジャ・ストライク",
    "STRIKE_BACK": "ストライク・バック",
    "REVOLUTION_0_TRIGGER": "革命0トリガー",

    # Cost / Reduction
    "MANA": "マナ",
    "TAP_CARD": "カードをタップ",
    "SACRIFICE_CARD": "カードを破壊",
    "RETURN_CARD": "手札に戻す",
    "SHIELD_BURN": "シールド焼却",
    "ACTIVE_PAYMENT": "アクション型軽減",
    "PASSIVE": "パッシブ型軽減",

    # Zones
    "HAND": "手札",
    "BATTLE_ZONE": "バトルゾーン",
    "GRAVEYARD": "墓地",
    "MANA_ZONE": "マナゾーン",
    "SHIELD_ZONE": "シールドゾーン",
    "DECK_BOTTOM": "デッキ下",
    "DECK_TOP": "デッキ上",
    "DECK": "デッキ",

    # Scopes
    "PLAYER_SELF": "自分",
    "PLAYER_OPPONENT": "相手",
    "TARGET_SELECT": "対象選択",
    "ALL_PLAYERS": "両プレイヤー",
    "RANDOM": "ランダム",
    "ALL_FILTERED": "全体(フィルタ)",
    "NONE": "なし",

    # Civilizations
    "LIGHT": "光",
    "WATER": "水",
    "DARKNESS": "闇",
    "FIRE": "火",
    "NATURE": "自然",
    "ZERO": "無色",

    # Labels
    "Destination Zone": "移動先ゾーン",
    "Keyword": "キーワード",
    "Duration (Turns)": "持続ターン数",
    "Race (e.g. Fire Bird)": "種族 (例: ファイアー・バード)",
    "Action Type": "アクションタイプ",
    "Scope": "対象スコープ",
    "String Value": "文字列値 (String Value)",
    "Mode": "モード",
    "Ref Mode": "参照モード",
    "Value 1": "値 1",
    "Value 2": "値 2",
    "Arbitrary Amount (Up to N)": "任意数 (N枚まで)",
    "Filter": "フィルタ",

    # Common
    "Name": "カード名",
    "Civilization": "文明",
    "Type": "タイプ",
    "ELEMENT": "エレメント",
    "Cost": "コスト",
    "Power": "パワー",
    "Races": "種族",
    "Keywords": "キーワード能力",
    "Twinpact": "ツインパクト",
    "Is Twinpact?": "ツインパクトにする",
    "--- Twinpact Spell Side ---": "--- ツインパクト呪文側 ---",
    "Spell Side Name": "呪文側の名前",
    "Effects for Spell side are managed in the tree.": "呪文側の効果は左のツリーで管理してください。",
    "AI Configuration": "AI設定",
    "Is Key Card / Combo Piece": "キーカード / コンボパーツ",
    "AI Importance Score": "AI優先度スコア",
    "Action": "アクション",

    # Filter
    "Basic Filter": "基本条件",
    "Stats Filter": "ステータス条件",
    "Flags Filter": "状態条件",
    "Selection": "選択数設定",
    "Zones:": "ゾーン:",
    "Types:": "カードタイプ:",
    "Civilizations:": "文明:",
    "Races:": "種族:",
    "Comma separated races (e.g. Dragon, Cyber Lord)": "カンマ区切り (例: ドラゴン, サイバーロード)",
    "Min:": "最小:",
    "Max:": "最大:",
    "Any": "指定なし",
    "Is Tapped?": "タップ状態?",
    "Is Blocker?": "ブロッカー?",
    "Is Evolution?": "進化?",
    "Card Designation": "カード指定(非エレメント)",
    "Ignore": "無視",
    "Yes (True)": "はい",
    "No (False)": "いいえ",
    "Selection Mode": "選択モード",
    "All/Any": "すべて/任意",
    "Selection_All": "すべて",
    "Selection_Any": "任意",
    "Fixed Number": "固定数",
    "Filter Help": "対象を選択するための条件を指定します。",
    "Include BATTLE_ZONE in target selection": "バトルゾーンを対象に含める",
    "Play without paying cost": "コストを支払わずにプレイする",

    # Reaction
    "Reaction Abilities": "リアクション能力 (手札誘発)",
    "Add": "追加",
    "Remove": "削除",
    "Reaction Details": "詳細設定",
    "Trigger Event": "トリガー条件",
    "Civilization Match Required": "文明一致が必要",
    "Min Mana Required": "必要マナ枚数",
    "Zone": "発動ゾーン",
    "Cost / Requirement": "コスト/条件値",
    "ON_BLOCK_OR_ATTACK": "ブロック時または攻撃時",

    # Keywords
    "Speed Attacker": "スピードアタッカー",
    "Blocker": "ブロッカー",
    "Slayer": "スレイヤー",
    "Double Breaker": "W・ブレイカー",
    "Triple Breaker": "T・ブレイカー",
    "Shield Trigger": "S・トリガー",
    "Evolution": "進化",
    "Just Diver": "ジャストダイバー",
    "Mach Fighter": "マッハファイター",
    "G Strike": "G・ストライク",
    "Hyper Energy": "ハイパーエナジー",
    "Shield Burn": "シールド焼却",
    "Revolution Change": "革命チェンジ",
    "Untap In": "アンタップイン",
    "Meta Counter": "メタカウンター",
    "Power Attacker": "パワーアタッカー",
    "Revolution Change Condition": "革命チェンジ条件設定",
    "OPPONENT_DRAW_COUNT": "相手ドロー枚数",
    "Add Reaction Ability": "リアクション能力を追加",
    "Reaction Ability": "リアクション能力",
    "W-Breaker": "W・ブレイカー",
    "T-Breaker": "T・ブレイカー",
    "G-Zero": "G・ゼロ",
    "CIP": "出た時 (CIP)",
    "At Attack": "攻撃時",
    "At Block": "ブロック時",
    "Start of Turn": "ターン開始時",
    "End of Turn": "ターン終了時",
    "On Destroy": "破壊された時",

    # Added for Ver 2.1
    "Spell Side": "呪文側",
    "Edit Spell Side Properties": "呪文側のプロパティ編集",
    "Add Revolution Change": "革命チェンジを追加",
    "Special Abilities": "特殊能力",
    "Enable to generate a Spell Side node in the logic tree.": "ロジックツリーに呪文側のノードを生成します。",
    "REVOLUTION_CHANGE": "革命チェンジ",
    "SPELL_SIDE": "呪文側",

    # App / Game Window
    "Game Info & Controls": "ゲーム情報 & 操作",
    "Game Status & Operations": "ゲームステータス & 操作",
    "Turn": "ターン",
    "Phase": "フェーズ",
    "Active": "アクティブ",
    "Start Sim": "シミュ開始",
    "Stop Sim": "シミュ停止",
    "Step": "ステップ",
    "Reset": "リセット",
    "AI & Tools": "AI & ツール",
    "Player Mode": "プレイヤーモード",
    "P0 (Self): Human": "P0 (自分): 人間",
    "P0 (Self): AI": "P0 (自分): AI",
    "P1 (Opp): Human": "P1 (相手): 人間",
    "P1 (Opp): AI": "P1 (相手): AI",
    "Deck Builder": "デッキビルダー",
    "Card Editor": "カードエディタ",
    "Scenario Editor": "シナリオエディタ",
    "Batch Simulation": "一括シミュレーション",
    "Deck Management": "デッキ管理",
    "Load Deck P0": "デッキ読込 P0",
    "Load Deck P1": "デッキ読込 P1",
    "God View": "ゴッドビュー (全公開)",
    "Help / Manual": "ヘルプ / マニュアル",
    "Logs": "ログ",
    "MCTS Analysis": "MCTS分析",
    "Invalid Deck": "無効なデッキ",
    "Deck must have 40 cards.": "デッキは40枚である必要があります。",
    "Failed to load deck": "デッキの読み込みに失敗しました",
    "Loaded Deck for P0": "P0のデッキを読み込みました",
    "Loaded Deck for P1": "P1のデッキを読み込みました",
    "Game Reset": "ゲームリセット",
    "No actions for card": "このカードで実行できるアクションはありません",
    "Multiple actions found. Executing first.": "複数のアクションが見つかりました。最初のアクションを実行します。",
    "Game Over! Result": "ゲームオーバー! 結果",
    "Auto-Pass": "自動パス",
    "AI Action": "AIアクション",
    "Simulation stopped.": "シミュレーション停止",
    "Error: MCTS returned None": "エラー: MCTSが結果を返しませんでした",
    "P1 Action": "P1 アクション",
    "P0 Action": "P0 アクション",

    # Deck Builder
    "Search...": "検索...",
    "New Card": "新規カード",
    "Preview": "プレビュー",
    "Deck": "デッキ",
    "Save Deck": "デッキ保存",
    "Load Deck": "デッキ読込",
    "Deck must have exactly 40 cards.": "デッキはちょうど40枚である必要があります。",
    "Deck saved!": "デッキを保存しました!",
    "Unknown": "不明",

    # Card Detail Panel
    "Card Name": "カード名",
    "Unknown Card": "不明なカード",
    "Card effects will appear here...": "カード効果がここに表示されます...",
}


def translate(key: str) -> str:
    """Return localized text when available, otherwise echo the key."""
    return TRANSLATIONS.get(key, key)


def tr(text: str) -> str:
    return TRANSLATIONS.get(text, text)
