# -*- coding: utf-8 -*-
"""
Constants for the Card Editor GUI.
This file defines command strings, internal event names, and data roles to ensure consistency
across the editor's forms and logic.
"""
try:
    from PyQt6.QtCore import Qt
    ROLE_TYPE = Qt.ItemDataRole.UserRole + 1
    ROLE_DATA = Qt.ItemDataRole.UserRole + 2
except ImportError:
    # Fallback values for headless environment
    # Qt.ItemDataRole.UserRole is 256 (0x0100)
    ROLE_TYPE = 257
    ROLE_DATA = 258

# Structural Command Constants
# Used for signaling structural changes from forms to the main editor
STRUCT_CMD_ADD_CHILD_EFFECT = "ADD_CHILD_EFFECT"
STRUCT_CMD_ADD_SPELL_SIDE = "ADD_SPELL_SIDE"
STRUCT_CMD_REMOVE_SPELL_SIDE = "REMOVE_SPELL_SIDE"
STRUCT_CMD_ADD_REV_CHANGE = "ADD_REV_CHANGE"
STRUCT_CMD_REMOVE_REV_CHANGE = "REMOVE_REV_CHANGE"
STRUCT_CMD_ADD_MEKRAID = "ADD_MEKRAID"
STRUCT_CMD_REMOVE_MEKRAID = "REMOVE_MEKRAID"
STRUCT_CMD_ADD_FRIEND_BURST = "ADD_FRIEND_BURST"
STRUCT_CMD_REMOVE_FRIEND_BURST = "REMOVE_FRIEND_BURST"
STRUCT_CMD_ADD_MEGA_LAST_BURST = "ADD_MEGA_LAST_BURST"
STRUCT_CMD_REMOVE_MEGA_LAST_BURST = "REMOVE_MEGA_LAST_BURST"
STRUCT_CMD_GENERATE_BRANCHES = "GENERATE_BRANCHES"
STRUCT_CMD_GENERATE_OPTIONS = "GENERATE_OPTIONS"
STRUCT_CMD_MOVE_EFFECT = "MOVE_EFFECT"
STRUCT_CMD_ADD_CHILD_ACTION = "ADD_CHILD_ACTION"
STRUCT_CMD_REPLACE_WITH_COMMAND = "REPLACE_WITH_COMMAND"
