# python/gui/localization.py

TRANSLATIONS = {
    # Window & Menus
    "Card Editor": "カードエディタ",
    "Load from JSON": "JSONから読み込み",
    "Save to JSON": "JSONへ保存",
    "File": "ファイル",
    "Edit": "編集",
    "Open": "開く",
    "Save": "保存",
    "Close": "閉じる",
    "New Card": "新規カード",
    "Delete Card": "カード削除",
    "Delete Item": "削除",
    "Preview": "プレビュー",
    "Action updated!": "アクションが更新されました！",
    "Cards saved successfully!": "カードが正常に保存されました！",
    "Error": "エラー",
    "Success": "成功",
    "Failed to load JSON": "JSONの読み込みに失敗しました",
    "Failed to save JSON": "JSONの保存に失敗しました",
    "Property Inspector": "プロパティ・インスペクタ",
    "Select an item to edit": "編集する項目を選択してください",
    "Main Toolbar": "メインツールバー",
    "Tools": "ツール",
    "Batch Simulation": "バッチシミュレーション",
    "Scenario Editor": "シナリオエディタ",

    # Batch Simulation
    "Batch Simulation / Verification": "バッチシミュレーション / 検証",
    "Settings": "設定",
    "Scenario": "シナリオ",
    "Evaluator": "評価器 (Evaluator)",
    "Games": "ゲーム数",
    "Threads": "スレッド数",
    "MCTS Sims": "MCTSシミュレーション数",
    "Run Simulation": "シミュレーション開始",
    "Cancel": "キャンセル",
    "Starting simulation": "シミュレーションを開始します",
    "Completed": "完了",
    "Wins": "勝利",
    "Losses": "敗北",
    "Draws": "引き分け",
    "Throughput": "スループット",
    "Simulation Error": "シミュレーションエラー",
    "Warning: No model_v1.pth found. Using random weights.": "警告: model_v1.pthが見つかりません。ランダムな重みを使用します。",

    # Scenario Editor
    "Scenarios": "シナリオ一覧",
    "Name (ID)": "名前 (ID)",
    "Description": "説明",
    "Configuration (JSON)": "設定 (JSON)",
    "Save All to File": "ファイルに保存",
    "Scenarios saved successfully!": "シナリオが正常に保存されました！",
    "New": "新規作成",
    "Delete": "削除",

    # Card Details
    "Card Details": "カード詳細",
    "ID": "ID",
    "Name": "名前",
    "Cost": "コスト",
    "Civilization": "文明",
    "Power": "パワー",
    "Type": "タイプ",
    "Races": "種族",

    # Lists & Groups
    "Keywords": "キーワード能力",
    "Effects": "効果リスト",
    "Add Effect": "効果を追加",
    "Remove Effect": "効果を削除",
    "Reaction Abilities": "リアクション能力", # Ninja Strike etc
    "REVOLUTION_CHANGE": "革命チェンジ",

    # Effect Definition
    "Effect": "効果",
    "Trigger": "トリガー",
    "Condition": "発動条件",
    "Actions": "アクションリスト",
    "Add Action": "アクションを追加",
    "Remove Action": "アクションを削除",

    # Action Definition
    "Action": "アクション",
    "Action Type": "アクションタイプ",
    "Scope": "対象範囲 (Scope)",
    "Target Player": "対象プレイヤー",
    "Source Zone": "移動元ゾーン",
    "Destination Zone": "移動先ゾーン",
    "Value 1": "値 1 (数)",
    "Value 2": "値 2",
    "String Value": "文字列値",
    "Input Key": "入力変数キー",
    "Output Key": "出力変数キー",
    "Optional": "任意効果",
    "Update Action": "アクション更新",
    "Reduction Amount": "軽減量",
    "Duration (Turns)": "持続ターン",

    # Filter Definition
    "Filter": "フィルタ",
    "Owner": "所有者",
    "Zones": "ゾーン",
    "Card Types": "カードタイプ",
    "Civilizations": "文明フィルタ",
    "Races": "種族フィルタ",
    "Min Cost": "最小コスト",
    "Max Cost": "最大コスト",
    "Min Power": "最小パワー",
    "Max Power": "最大パワー",
    "Min": "最小",
    "Max": "最大",
    "Tapped": "タップ状態",
    "Blocker": "ブロッカー",
    "Evolution": "進化",
    "Count": "枚数",
    "Ignore": "指定なし",
    "True": "はい",
    "False": "いいえ",
    "Selection Mode": "選択モード",
    "All/Any": "すべて / 任意",
    "Fixed Number": "枚数指定",

    # Common Values
    "NONE": "なし",
    "CREATURE": "クリーチャー",
    "SPELL": "呪文",
    "EVOLUTION_CREATURE": "進化クリーチャー",
    "LIGHT": "光",
    "WATER": "水",
    "DARKNESS": "闇",
    "FIRE": "火",
    "NATURE": "自然",
    "ZERO": "ゼロ",

    # Enums - Triggers
    "ON_PLAY": "登場時 (ON_PLAY)",
    "ON_ATTACK": "攻撃時 (ON_ATTACK)",
    "ON_DESTROY": "破壊時 (ON_DESTROY)",
    "S_TRIGGER": "S・トリガー",
    "TURN_START": "ターン開始時",
    "PASSIVE_CONST": "常在効果",
    "ON_OTHER_ENTER": "他クリーチャー登場時",
    "ON_ATTACK_FROM_HAND": "手札から攻撃時 (革命チェンジ等)",

    # Enums - Conditions
    "MANA_ARMED": "マナ武装",
    "SHIELD_COUNT": "シールド枚数",
    "CIVILIZATION_MATCH": "文明一致",
    "OPPONENT_PLAYED_WITHOUT_MANA": "相手がマナを払わずにプレイ",

    # Enums - Actions
    "DRAW_CARD": "ドロー",
    "ADD_MANA": "マナ加速",
    "DESTROY": "破壊",
    "RETURN_TO_HAND": "手札に戻す (バウンス)",
    "SEND_TO_MANA": "マナ送りにする",
    "TAP": "タップする",
    "UNTAP": "アンタップする",
    "MODIFY_POWER": "パワー修正",
    "BREAK_SHIELD": "シールドブレイク",
    "LOOK_AND_ADD": "見て手札に加える",
    "SUMMON_TOKEN": "トークン召喚",
    "SEARCH_DECK_BOTTOM": "山札下サーチ",
    "MEKRAID": "メクレイド",
    "DISCARD": "手札を捨てる",
    "PLAY_FROM_ZONE": "ゾーンからプレイ",
    "COST_REFERENCE": "コスト参照/軽減",
    "LOOK_TO_BUFFER": "バッファへ見る",
    "SELECT_FROM_BUFFER": "バッファから選択",
    "PLAY_FROM_BUFFER": "バッファからプレイ",
    "MOVE_BUFFER_TO_ZONE": "バッファから移動",
    "REVOLUTION_CHANGE": "革命チェンジ",
    "COUNT_CARDS": "カードを数える",
    "GET_GAME_STAT": "ゲーム統計取得",
    "APPLY_MODIFIER": "修正を適用 (継続効果)",
    "REVEAL_CARDS": "カードを公開",
    "REGISTER_DELAYED_EFFECT": "遅延効果登録",
    "RESET_INSTANCE": "カード状態リセット",
    "Hyper Energy": "ハイパーエナジー",
    "SEND_TO_DECK_BOTTOM": "山札下へ送る",

    # Smart Link
    "Use result from previous measurement": "直前の計測結果を使用する",
    "Cards matching filter": "フィルターに一致する枚数",

    # Game Stats
    "MANA_CIVILIZATION_COUNT": "マナゾーンの文明数",
    "SHIELD_COUNT": "シールド枚数",
    "HAND_COUNT": "手札枚数",

    # Filter Help
    "Filter Help": "対象を選択するゾーンを指定してください。「枚数」を0にすると「すべて/任意」になります。1以上にするとその枚数を選択します。",

    # Scope
    "PLAYER_SELF": "自分",
    "PLAYER_OPPONENT": "相手",
    "TARGET_SELECT": "選択",
    "ALL_PLAYERS": "両者",
    "RANDOM": "ランダム",
    "ALL_FILTERED": "全て(フィルタ)",

    # Zones
    "BATTLE_ZONE": "バトルゾーン",
    "MANA_ZONE": "マナゾーン",
    "HAND": "手札",
    "GRAVEYARD": "墓地",
    "SHIELD_ZONE": "シールドゾーン",
    "DECK": "山札",

    # Keywords
    "Speed Attacker": "スピードアタッカー",
    "Blocker": "ブロッカー",
    "Slayer": "スレイヤー",
    "Double Breaker": "W・ブレイカー",
    "Triple Breaker": "T・ブレイカー",
    "Shield Trigger": "S・トリガー",
    "Just Diver": "ジャストダイバー",
    "Mach Fighter": "マッハファイター",
    "G Strike": "G・ストライク",
    "Evolution": "進化",
}

def tr(text):
    return TRANSLATIONS.get(text, text)
