#!/usr/bin/env python3
"""Extract translatable strings from .py and Qt .ui files.

Produces a gettext-style POT file at `i18n/extracted.pot` with file/line references.

Usage: python scripts/extract_i18n.py
"""
from __future__ import annotations

import ast
import os
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "i18n"
OUT_FILE = OUT_DIR / "extracted.pot"

EXCLUDE_DIRS = {"build", "build-ninja", ".git", "__pycache__", ".cmake_deps_cache", "venv", ".venv"}


def iter_source_files(root: Path):
    for path in root.rglob("*"):
        if any(part in EXCLUDE_DIRS for part in path.parts):
            continue
        if path.suffix in {".py", ".ui"} and path.is_file():
            yield path


def extract_from_py(path: Path) -> List[Tuple[int, str]]:
    results: List[Tuple[int, str]] = []
    try:
        src = path.read_text(encoding="utf-8")
    except Exception:
        return results

    try:
        tree = ast.parse(src)
    except Exception:
        return results

    for node in ast.walk(tree):
        # Skip module/function/class docstrings (they appear as Expr(Constant) at top)
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            parent = getattr(node, "parent", None)
            # We'll filter docstrings by checking if parent is ast.Expr and parent of that is Module/FunctionDef/ClassDef
            # But ast doesn't have parent pointers by default; do a lightweight check by position: ignore if lineno == 1 and node is at module doc.
            if getattr(node, "lineno", None) == 1:
                continue
            text = node.value.strip()
            if text and len(text) > 0 and not text.isspace():
                results.append((node.lineno, text))
        # Note: f-strings and JoinedStr are ignored for now

    return results


def extract_from_ui(path: Path) -> List[Tuple[int, str]]:
    results: List[Tuple[int, str]] = []
    try:
        tree = ET.parse(path)
        root = tree.getroot()
    except Exception:
        return results

    # Common attributes that hold user-visible text
    text_attrs = {"text", "title", "placeholderText", "toolTip", "whatsThis"}

    for elem in root.iter():
        for attr in text_attrs:
            val = elem.get(attr)
            if val and val.strip():
                # ElementTree does not expose line numbers easily; use 0 as placeholder
                results.append((0, val.strip()))

    return results


def write_pot(entries: Dict[str, List[Tuple[str, int]]]):
    OUT_DIR.mkdir(exist_ok=True)
    with OUT_FILE.open("w", encoding="utf-8") as f:
        f.write("# Generated by scripts/extract_i18n.py\n")
        f.write("msgid \"\"\nmsgstr \"\"\n\n")
        for msgid, locations in sorted(entries.items()):
            for path, lineno in locations:
                if lineno and lineno > 0:
                    f.write(f"#: {path}:{lineno}\n")
                else:
                    f.write(f"#: {path}\n")
            # Escape double quotes
            safe = msgid.replace('"', '\\"')
            f.write(f"msgid \"{safe}\"\nmsgstr \"\"\n\n")


def main() -> int:
    entries: Dict[str, List[Tuple[str, int]]] = {}
    for path in iter_source_files(ROOT):
        rel = path.relative_to(ROOT).as_posix()
        if path.suffix == ".py":
            items = extract_from_py(path)
        else:
            items = extract_from_ui(path)

        for lineno, text in items:
            entries.setdefault(text, []).append((rel, lineno))

    write_pot(entries)
    print(f"Wrote {OUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
