# PowerShell helper to run the GUI with a real PyQt6 installation.
# Usage:
#  - Run from project root with venv activated: `.


































































exit $code}    Write-Host "  Rename-Item -Path .\PyQt6_stub_YYYYMMDDHHMMSS -NewName PyQt6"    Write-Host "To restore, run (example):"    Write-Host "  Get-ChildItem -Directory -Name (Join-Path (Split-Path $stubPath.Path -Parent)) | Where-Object { \'PyQt6_stub_\' -in $_ }"    Write-Host "If you want to restore the original stub, run this to list backups:"if ($stubPath -and -not $NoRename -and -not $KeepStub) {# 4) If we renamed the stub, offer to restore itWrite-Host "GUI launcher exited with code $code"$code = $LASTEXITCODE& $runScript# Execute and forward output}    exit 1    Write-Error "Could not find run_gui.ps1 in scripts/. Aborting."if (-not (Test-Path $runScript)) {$runScript = Join-Path -Path $PSScriptRoot -ChildPath "run_gui.ps1"Write-Host "Launching GUI script..."# 3) Run the GUI launcher}    Write-Host "Local PyQt6 stub detected but left in place (KeepStub). This may prevent real PyQt6 from loading."} elseif ($stubPath -and $KeepStub) {    }        exit 1        Write-Error "Failed to rename stub: $_"    } catch {        Rename-Item -Path $stubFull -NewName (Split-Path $backup -Leaf)    try {    Write-Host "Renaming local PyQt6 stub: '$stubFull' -> '$backup'"    $backup = Join-Path -Path (Split-Path $stubFull) -ChildPath "PyQt6_stub_$(Get-Date -Format yyyyMMddHHmmss)"    $stubFull = $stubPath.Pathif ($stubPath -and -not $NoRename -and -not $KeepStub) {$stubPath = Join-Path -Path $PSScriptRoot -ChildPath "..\PyQt6" | Resolve-Path -ErrorAction SilentlyContinue# 2) If a local PyQt6 stub folder exists, rename it out of the way unless NoRename or KeepStub}    }        exit $LASTEXITCODE        Write-Error "pip install failed. Aborting."    if ($LASTEXITCODE -ne 0) {    & $python -m pip install PyQt6    & $python -m pip install --upgrade pip    Write-Host "Installing PyQt6 into current environment (pip install PyQt6)..."if (-not $NoInstall) {}    exit 1    Write-Error "No 'python' on PATH. Activate your virtualenv first (e.g. . .\ .venv\Scripts\Activate.ps1)."if (-not $python) {$python = (Get-Command python -ErrorAction SilentlyContinue).Source# 1) ensure venv's python/pip are usedWrite-Host "Run GUI with real PyQt6 helper")    [switch]$KeepStub    [switch]$NoRename,    [switch]$NoInstall,param(#  - Options: -NoInstall (skip pip install), -NoRename (don't rename local PyQt6 stub), -KeepStub (leave stub as-is but still try to run)un_gui_with_real_pyqt.ps1`